//LOCALHOST
// Get All Data with localhost
###
GET http://localhost:8080/contacts HTTP/1.1

// Get Single Data with localhost
### 
GET http://localhost:8080/contacts/643ee4f5c2945ed3d476146f HTTP/1.1
###
GET http://localhost:8080/contacts/643ee5ebc2945ed3d4761470 HTTP/1.1
###
GET http://localhost:8080/contacts/6449e48b331772b7c8c1e94e HTTP/1.1

// Create a new Contact
###
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Emilia",
    "lastName": "Suarez",
    "email": "emiliasuarez@test.com",
    "favoriteColor": "Red",
    "birthday": "12/30/1998"
}

// Update contact by ID
###
PUT http://localhost:8080/contacts/6449e48b331772b7c8c1e94e HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alex",
    "lastName": "Megan",
    "email": "alexmegan@test.com",
    "favoriteColor": "Green",
    "birthday": "10/23/1996"
}

// Delete a contact
###
DELETE http://localhost:8080/contacts/6449e48b331772b7c8c1e94e HTTP/1.1



//PRODUCTION WITH RENDER
// Get all Data with deploy production
###
GET https://personal-assignmentw01.onrender.com/contacts HTTP/1.1

/// Get Single data with deploy production
###
GET https://personal-assignmentw01.onrender.com/contacts/643ee4f5c2945ed3d476146f HTTP/1.1
###
GET https://personal-assignmentw01.onrender.com/contacts/643ee5ebc2945ed3d4761470 HTTP/1.1
###
GET https://personal-assignmentw01.onrender.com/contacts/6449e57c8231104cc9b98121 HTTP/1.1

// Create a new Contact with Render Link
###
POST https://personal-assignmentw01.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alex",
    "lastName": "McKay",
    "email": "alexmckay@test.com",
    "favoriteColor": "Yellow",
    "birthday": "10/25/1997"
}

// Update contact by ID with Render Link
###
PUT https://personal-assignmentw01.onrender.com/contacts/6449e57c8231104cc9b98121 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kevin",
    "lastName": "Mckay",
    "email": "kevinmckay@test.com",
    "favoriteColor": "Sky Blue",
    "birthday": "08/30/1997"
}

// Delete a contact with Render Link
###
DELETE https://personal-assignmentw01.onrender.com/contacts/6449e929a2e74451b0c32561 HTTP/1.1